<?php
    $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false');
    $this->headScript()->appendFile($this->basePath('/World/js/googlemap.js'));
    $this->headLink()->prependStylesheet($this->basePath('/World/css/googlemap.css'));
?>
    <?php
    $this->headScript()->captureStart() ?>
    var COUNTRY = '<?php echo $country->getName()?>';
    <?php $this->headScript()->captureEnd() ;
?>
    <h1><?php echo $country->getName()?></h1>
    <?php
foreach ($getters as $getter){
    
}
    ?>
<div id="map-canvas" style=""></div>