    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    
    <style>
        #map-canvas{ height:400px
        }
#map-canvas img {
     max-width: none!important; 
}
#map-canvas label {
  width: auto; display:inline;
}
	    
        </style>
    <script>
                    
var map;
function initialize() {
  var mapOptions = {
    zoom: 8,
    center: new google.maps.LatLng(61.52401, 105.318756),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
}

google.maps.event.addDomListener(window, 'load', initialize);
    </script>

    <div id="map-canvas" style=""></div>
